import java.sql.*;
import javax.swing.*;
public class certificate extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rst;

    /**
     * Creates new form certificate
     */
    public certificate() {
        initComponents();
        conn=bbm_class.bbm_class1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 255, 51));
        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 28)); // NOI18N
        jLabel1.setText("Cirtificate Of Apreciation");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 20, 338, 29);

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 0, 29)); // NOI18N
        jLabel2.setText("We are pleased to appreciate the noble gesture of");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 400, 35);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(420, 70, 500, 28);

        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 0, 29)); // NOI18N
        jLabel3.setText("for organizing a Voluntary  Blood Duration");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 390, 34);

        jLabel4.setFont(new java.awt.Font("Edwardian Script ITC", 0, 29)); // NOI18N
        jLabel4.setText("Camp at");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 160, 160, 35);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(110, 160, 255, 28);

        jLabel5.setFont(new java.awt.Font("Edwardian Script ITC", 0, 29)); // NOI18N
        jLabel5.setText("on");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 160, 100, 35);

        jLabel7.setFont(new java.awt.Font("Edwardian Script ITC", 0, 29)); // NOI18N
        jLabel7.setText("This social service shown by your oraganization towards the needy patients may  please be continued. ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 210, 790, 35);

        jLabel8.setFont(new java.awt.Font("Edwardian Script ITC", 0, 29)); // NOI18N
        jLabel8.setText("Date");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 270, 130, 35);

        jTextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField4.setToolTipText("");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(420, 160, 163, 28);

        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 270, 156, 28);

        jLabel9.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel9.setText("Medical Officer");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 320, 150, 30);

        jLabel11.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel11.setText("Hospital Blood Bank");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(180, 340, 210, 41);

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel12.setText("Member_Secretary");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(760, 330, 170, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/10708924-Elegant-vintage-background--Stock-Vector-border-frame-certificate.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-260, -370, 1344, 860);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-49, -9, 50, 10);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -1, 980, 480));

        setSize(new java.awt.Dimension(996, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new certificate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
