import java.sql.*;
import javax.swing.*;
public class donor_detail_form extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rst;
    String sl1="";
    String sql2="";

    /**
     * Creates new form donor_detail_form
     */
    public donor_detail_form() {
        initComponents();
        conn=bbm_class.bbm_class1();
        num.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        m1 = new javax.swing.JRadioButton();
        f1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bg = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sup = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        past = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        date = new javax.swing.JFormattedTextField();
        cont = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(2, 37, 880, 10);

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donor's Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 50, 142, 25);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 130, 47, 23);

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 180, 64, 23);

        name.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(120, 130, 245, 29);

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Father's Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 290, 105, 23);

        f.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jPanel1.add(f);
        f.setBounds(120, 290, 245, 29);

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mother's Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 330, 110, 23);

        m.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jPanel1.add(m);
        m.setBounds(120, 330, 245, 29);

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact no. :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 370, 87, 23);

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 420, 58, 23);

        buttonGroup1.add(m1);
        m1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setText("Male");
        jPanel1.add(m1);
        m1.setBounds(120, 410, 57, 31);

        buttonGroup1.add(f1);
        f1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        f1.setText("Female");
        jPanel1.add(f1);
        f1.setBounds(120, 450, 75, 31);

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 50, 39, 23);

        age.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jPanel1.add(age);
        age.setBounds(610, 50, 110, 29);

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Blood Group :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 90, 94, 23);

        bg.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        bg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------SELECT--------", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgActionPerformed(evt);
            }
        });
        jPanel1.add(bg);
        bg.setBounds(610, 90, 250, 29);

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Past Disease details(if any) :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 130, 188, 23);

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Donated unde supervision of :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 270, 206, 23);

        sup.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supActionPerformed(evt);
            }
        });
        jPanel1.add(sup);
        sup.setBounds(610, 270, 250, 29);

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date of donation :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(480, 330, 123, 23);

        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Units of blood donation :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(430, 370, 171, 23);

        unit.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jPanel1.add(unit);
        unit.setBounds(610, 370, 250, 29);

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Donor Detail Form");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(36, 13, 146, 21);

        jButton1.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N
        jButton1.setText("SAVE DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 430, 135, 31);

        jLabel16.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Donor no.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 90, 69, 23);

        num.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jPanel1.add(num);
        num.setBounds(120, 90, 130, 29);

        past.setColumns(20);
        past.setRows(5);
        jScrollPane2.setViewportView(past);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(610, 130, 250, 123);

        add.setColumns(20);
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 170, 250, 110);

        try {
            date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(date);
        date.setBounds(610, 320, 250, 30);

        try {
            cont.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(cont);
        cont.setBounds(120, 370, 250, 30);

        jButton2.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(720, 470, 69, 31);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8n.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, -20, 910, 550);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(120, 180, 166, 96);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 510);

        setSize(new java.awt.Dimension(902, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supActionPerformed

    private void bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sex="";
        if (m1.isSelected()==(true))
            sex=m1.getText();
        if(f1.isSelected()==(true))
            sex=f1.getText();
        String sql="insert into donor ("
                +"name,"
                +"address,"
                +"fname,"
                +"mname,"
                +"number,"
                +"gender,"
                +"age,"
                +"bg,"
                +"disease,"
                +"supervision,"
                +"date,"
                +"unit)"
                +"values('"+name.getText()+"','"+add.getText()+"','"+f.getText()+"','"+m.getText()+"','"+cont.getText()+"','"+sex+"','"+age.getText()+"','"+bg.getSelectedItem().toString()+"','"+past.getText()+"','"+sup.getText()+"','"+date.getText()+"','"+unit.getText()+"')";
        try
        {
            pst=conn.prepareStatement(sql);
            pst.execute();
            String sql2="Update blood_group set d_unit='"+unit.getText()+"' where bg='"+bg.getSelectedItem().toString()+"'";
            try
            {
                pst=conn.prepareStatement(sql2);
                pst.executeUpdate();
            }
            catch(Exception ex)
            {
                System.out.println(ex);
            }
            String sql1="select * from donor where number = '"+cont.getText()+"'";
            try
            {
                pst=conn.prepareStatement(sql1);
                rst=pst.executeQuery();
                if(rst.next())
                {
                    String x=rst.getString("dn");
                    num.setText(""+x);
                    JOptionPane.showMessageDialog(this,"DONOR number is  "+x);
                    JOptionPane.showMessageDialog(this,"Data saved ...Thank you");
                    
                }
            }
            catch (Exception ex)
            {
                System.out.println(ex);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.hide();
        new main_form().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donor_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donor_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donor_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donor_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donor_detail_form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField cont;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JTextField f;
    private javax.swing.JRadioButton f1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField m;
    private javax.swing.JRadioButton m1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField num;
    private javax.swing.JTextArea past;
    private javax.swing.JTextField sup;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
