import java.sql.*;
import javax.swing.*;
public class receiver_detail_form extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rst;
            String sql2="";
            int i,z,x=0;
           

    /**
     * Creates new form receiver_detail_form
     */
    public receiver_detail_form() {
        initComponents();
        conn=bbm_class.bbm_class1();
         rn.setEditable(false);
         //String sql1="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bg = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        dname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        medical = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        rn = new javax.swing.JTextField();
        purpose = new javax.swing.JTextField();
        time = new javax.swing.JFormattedTextField();
        date = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 45, 918, -1));

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Receiver's Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        name.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 245, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Father's Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        f.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        f.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 245, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mother's Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, -1));

        m.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        m.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 245, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Purpose of  blood :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of receive :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time of receive :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 94, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Blood Group :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 135, -1, -1));

        bg.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        bg.setForeground(new java.awt.Color(51, 51, 51));
        bg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------SELECT--------", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgActionPerformed(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 132, 272, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Doctors name :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 182, -1, -1));

        dname.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        dname.setForeground(new java.awt.Color(51, 51, 51));
        dname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnameActionPerformed(evt);
            }
        });
        jPanel1.add(dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 179, 272, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Name of medical institution : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 229, -1, -1));

        medical.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        medical.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 226, 272, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Units of blood receiving :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 276, -1, -1));

        unit.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        unit.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 272, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Receiver Detail Form");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 13, -1, -1));

        jButton1.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N
        jButton1.setText("SAVE DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 367, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Receiver no. :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 100, -1));

        rn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        rn.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(rn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 120, -1));

        purpose.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        purpose.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(purpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 245, -1));

        time.setForeground(new java.awt.Color(51, 51, 51));
        time.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 92, 272, 29));

        date.setForeground(new java.awt.Color(51, 51, 51));
        try {
            date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 245, 29));

        add.setColumns(20);
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 250, 100));

        jButton2.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r33.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 960, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(942, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgActionPerformed

    private void dnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql="insert into receiver ("
                +"name,"
                +"address,"
                +"fname,"
                +"mname,"
                +"purpose,"
                +"date,"
                +"time,"
                +"bg,"
                +"dname,"
                +"medical,"
                +"unit)"
                +"values('"+name.getText()+"','"+add.getText()+"','"+f.getText()+"','"+m.getText()+"','"+purpose.getText()+"','"+date.getText()+"','"+time.getText()+"','"+bg.getSelectedItem().toString()+"','"+dname.getText()+"','"+medical.getText()+"','"+unit.getText()+"')";
      try
        {
            pst=conn.prepareStatement(sql);
            pst.execute();
            String sql2="Update blood_group set r_unit='"+unit.getText()+"' where bg='"+bg.getSelectedItem().toString()+"'";
            try
            {
                pst=conn.prepareStatement(sql2);
                pst.executeUpdate();
            }
            catch(Exception ex)
            {
                System.out.println(ex);
            }
            String sql1="select * from receiver where time = '"+time.getText()+"'";
            try
            {
                pst=conn.prepareStatement(sql1);
                rst=pst.executeQuery();
                if(rst.next())
                {
                    String x=rst.getString("en");
                    time.setText(""+x);
                    JOptionPane.showMessageDialog(this,"RECEIVER number is  "+x);
                    JOptionPane.showMessageDialog(this,"Data saved ...Thank you");
                    
                }
            }
            catch (Exception ex)
            {
                System.out.println(ex);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.hide();
        new main_form().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receiver_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receiver_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receiver_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receiver_detail_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receiver_detail_form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JComboBox bg;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JTextField dname;
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField m;
    private javax.swing.JTextField medical;
    private javax.swing.JTextField name;
    private javax.swing.JTextField purpose;
    private javax.swing.JTextField rn;
    private javax.swing.JFormattedTextField time;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
