import javax.swing.*;
import java.sql.*;
public class user_registration extends javax.swing.JFrame {
     Connection conn;
    PreparedStatement pst ;
    ResultSet rst ;
    String x = "";

    /**
     * Creates new form user_registration
     */
    public user_registration() {
        initComponents();
        conn=bbm_class.bbm_class1();
        id.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        m1 = new javax.swing.JRadioButton();
        f1 = new javax.swing.JRadioButton();
        em = new javax.swing.JTextField();
        num = new javax.swing.JFormattedTextField();
        c = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        pa = new javax.swing.JPasswordField();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2), "User Registration", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bradley Hand ITC", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 90, 78, 24);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel2.setText("Middle Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 140, 97, 24);

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 190, 76, 24);

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 240, 54, 24);

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel5.setText("E_mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 290, 46, 24);

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel6.setText("Contact number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 330, 120, 24);

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel7.setText("City");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 380, 29, 24);

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel8.setText("User Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 430, 79, 24);

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel9.setText("Passward");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 480, 67, 24);

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel10.setText("User id");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 40, 79, 24);

        f.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        jPanel1.add(f);
        f.setBounds(220, 90, 253, 30);

        m.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jPanel1.add(m);
        m.setBounds(220, 140, 253, 30);

        l.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jPanel1.add(l);
        l.setBounds(220, 190, 253, 30);

        buttonGroup1.add(m1);
        m1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        m1.setText("Male");
        jPanel1.add(m1);
        m1.setBounds(220, 240, 59, 33);

        buttonGroup1.add(f1);
        f1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        f1.setText("Female");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        jPanel1.add(f1);
        f1.setBounds(320, 240, 77, 33);

        em.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jPanel1.add(em);
        em.setBounds(220, 290, 254, 30);

        try {
            num.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(num);
        num.setBounds(220, 330, 254, 28);

        c.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jPanel1.add(c);
        c.setBounds(220, 380, 254, 30);

        un.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jPanel1.add(un);
        un.setBounds(220, 420, 254, 30);
        jPanel1.add(pa);
        pa.setBounds(220, 470, 254, 26);

        id.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jPanel1.add(id);
        id.setBounds(220, 40, 254, 30);

        jButton1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(443, 536, 67, 31);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blood-bank.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-160, 20, 470, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f1ActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sex="";
        if(m1.isSelected()==(true))
            sex=m1.getText();
        if(f1.isSelected()==(true))
            sex=f1.getText();
        String sql = "insert into user("
                +"fname,"
                +"mname,"
                +"lname,"
                +"gender,"
                +"email,"
                +"contact,"
                +"city,"
                +"user_name,"
                +"pw)"
                +"values('"+f.getText()+"','"+m.getText()+"','"+l.getText()+"','"+sex+"','"+em.getText()+"','"+num.getText()+"','"+c.getText()+"','"+un.getText()+"','"+pa.getText()+"')";
        try
        {
            pst=conn.prepareStatement(sql);
            pst.execute();
            String sql1= "select * from user where contact='"+num.getText()+"'";
            try
            {
                pst=conn.prepareStatement(sql1);
                rst=pst.executeQuery();
                if(rst.next())
                {
                    String x=rst.getString("id");
                    num.setText(""+x);
                    JOptionPane.showMessageDialog(this,"Your User id is  "+x);
                    //JOptionPane.showMessageDialog(this,"Data saved ...Thank you");
                    
                }
            }
            catch (Exception ex)
            {
                System.out.println(ex);
            }
            //JOptionPane.showMessageDialog(this,"USER NAME ='"+un.getText()+"'");
            JOptionPane.showMessageDialog(this,"Registered...");
            this.hide();
            new user_registration().setVisible(true);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField c;
    private javax.swing.JTextField em;
    private javax.swing.JTextField f;
    private javax.swing.JRadioButton f1;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField l;
    private javax.swing.JTextField m;
    private javax.swing.JRadioButton m1;
    private javax.swing.JFormattedTextField num;
    private javax.swing.JPasswordField pa;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
